# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: .*\.ipynb$
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
      - id: black-jupyter
        name: black-jupyter
        entry: black
        language: system
        types: [ jupyter ]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
#  - repo: https://github.com/nbQA-dev/nbQA
#    rev: 1.7.0
#    hooks:
#      - id: nbqa-pylint
