"""
TODO Oleksandr: docstring
"""

from typing import Any, Optional

from miniagents.messages import Message


class UserMessage(Message):
    """
    TODO Oleksandr: docstring
    """

    role: str = "user"


class SystemMessage(Message):
    """
    TODO Oleksandr: docstring
    """

    role: str = "system"


class AssistantMessage(Message):
    """
    A message generated by a language model.
    """

    role: str = "assistant"
    model: Optional[str] = None


def message_to_llm_dict(message: Message) -> dict[str, Any]:
    """
    TODO Oleksandr: docstring
    """
    # TODO Oleksandr: introduce a lambda function to derive roles from messages ?
    try:
        role = message.role
    except AttributeError:
        role = "user"

    return {
        "role": role,
        "content": str(message),
    }
